name: Deploy to VPS

on:
  push:
    branches: [ main ]  # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd ./jonang-monastery-payload
          git pull origin main
          docker buildx build -t jonang-payload:latest --load .
          docker stop jonang-payload || true
          docker rm jonang-payload || true
          docker run -d --name jonang-payload -p 3000:3000 jonang-payload:latest
